let translations = {}

translations['en'] = {}
translations['nl'] = {}
translations['de'] = {}
translations['sv'] = {}

translations['en']['close'] = "Close"
translations['en']['cancel'] = "Cancel"
translations['en']['refresh'] = "Refresh"
translations['en']['trashItem'] = "Trash"
translations['en']['moveItem'] = "Move"
translations['en']['myCloud'] = "My Cloud"
translations['en']['loginTitle'] = "Sign in"
translations['en']['registerTitle'] = "Create an account"
translations['en']['or'] = "or"
translations['en']['loginButton'] = "Sign in"
translations['en']['registerButton'] = "Create account"
translations['en']['registerLink'] = "Create an account (First 10 GB free)"
translations['en']['loginLink'] = "Sign in"
translations['en']['passwordRepeatPlaceholder'] = "Repeat password"
translations['en']['emailPlaceholder'] = "Email address"
translations['en']['passwordPlaceholder'] = "Password"
translations['en']['2faPlaceholder'] = "2FA code (leave empty if disabled)"
translations['en']['loginInvalidInputs'] = "Invalid email address and password"
translations['en']['alertOkButton'] = "OK"
translations['en']['loginWrongCredentials'] = "Wrong email, password or 2FA code"
translations['en']['apiRequestError'] = "Request error, please try again later"
translations['en']['registerInvalidFields'] = "Invalid form fields"
translations['en']['registerPasswordAtLeast10Chars'] = "Your password needs to be at least 10 characters long"
translations['en']['registerPasswordsDoNotMatch'] = "Passwords do not match"
translations['en']['registerInvalidEmail'] = "Invalid email address"
translations['en']['registerEmailAlreadyRegistered'] = "This email address is already registered"
translations['en']['registerCouldNotSendEmail'] = "We could not send an email at this time, please try again later"
translations['en']['registerSuccess'] = "Account created, please confirm your email address by clicking the link we've sent to you"
translations['en']['registerInvalidInputs'] = "Invalid email address, password and confirm password"
translations['en']['sharedWithMe'] = "Shared with me"
translations['en']['currentlySharing'] = "Currently sharing"
translations['en']['settings'] = "Settings"
translations['en']['encryption'] = "Encryption"
translations['en']['help'] = "Help"
translations['en']['trash'] = "Trash"
translations['en']['userStorageUsageMenuText'] = "__PERCENTAGE__% of __MAX__ used"
translations['en']['goProBadge'] = "Go Pro"
translations['en']['unknownDeviceError'] = "An unknown error occured on your device, try restarting the app or contact our support for help"
translations['en']['uploadInvalidFileSize'] = "__NAME__ has an invalid file size"
translations['en']['fileUploadFileAlreadyExists'] = "__NAME__ already exists in this folder"
translations['en']['fileUploadStarted'] = "__NAME__ upload started"
translations['en']['fileUploadCouldNotReadFile'] = "Could not read __NAME__, cancelling upload"
translations['en']['couldNotImportKeys'] = "Could not import your keypair, please try again or contact support"
translations['en']['fileUploadFailed'] = "Could not upload __NAME__, check your internet connection or contact support"
translations['en']['fileUploadDone'] = "__NAME__ uploaded successfully"
translations['en']['fileUploadInvalidFileName'] = "__NAME__ has an invalid name"
translations['en']['fileDownloadAlreadyDownloadingFile'] = "__NAME__ is already being downloaded"
translations['en']['fabUploadFiles'] = "Upload files"
translations['en']['fabCreateFolder'] = "Create folder"
translations['en']['couldNotGetDownloadDir'] = "Could not get download directory, please restart your app/device or contact support"
translations['en']['fileDownloadStarted'] = "__NAME__ download started"
translations['en']['fileDownloadError'] = "__NAME__ download failed"
translations['en']['downloadItem'] = "Download"
translations['en']['moveItem'] = "Move"
translations['en']['renameItem'] = "Rename"
translations['en']['makeItemAvailableOffline'] = "Make available offline"
translations['en']['shareItem'] = "Share"
translations['en']['fileWriteError'] = "Could not write __NAME__ to local filesystem, please restart your app/device or contact support"
translations['en']['fileIsNowAvailableOffline'] = "__NAME__ is now available offline"
translations['en']['fileDownloadDone'] = "__NAME__ download done"
translations['en']['removeItemFromOffline'] = "Remove from offline storage"
translations['en']['couldNotDeleteDownloadedFile'] = "Could not delete __NAME__ from local filesystem, please restart your app/device or contact support"
translations['en']['fileDeletedFromOfflineStorage'] = "__NAME__ deleted from offline storage"
translations['en']['selectDestination'] = "Select destination"
translations['en']['fileNoPreviewAvailable'] = "No preview available for __NAME__"
translations['en']['loadingPreview'] = "Loading preview.."
translations['en']['noAppFoundToOpenFile'] = "No app found on the device to open __NAME__"
translations['en']['cannotMoveFileHere'] = "You cannot move this file here"
translations['en']['fileMoveAlreadyExistsHere'] = "__NAME__ already exists in this folder"
translations['en']['fileMoved'] = "__NAME__ moved"
translations['en']['thisFolderCannotBeMoved'] = "This folder cannot be moved"
translations['en']['folderMoveAlreadyExistsHere'] = "__NAME__ already exists in this folder"
translations['en']['folderMoved'] = "__NAME__ moved"
translations['en']['moveFileOrFolderSameDestination'] = "Cannot move to the same folder as before"
translations['en']['selectAll'] = "Select all"
translations['en']['unselectAll'] = "Unselect all"
translations['en']['renameFile'] = "Rename file"
translations['en']['renameFolder'] = "Rename folder"
translations['en']['folderRenameAlreadyExists'] = "__NAME__ already exists in this folder"
translations['en']['couldNotRenameFolder'] = "Could not rename the folder, please try again or contact support"
translations['en']['folderRenamed'] = "__NAME__ renamed to __TO__"
translations['en']['fileRenameAlreadyExists'] = "__NAME__ already exists in this folder"
translations['en']['couldNotRenameFile'] = "Could not rename the file, please try again or contact support"
translations['en']['fileRenamed'] = "__NAME__ renamed to __TO__"
translations['en']['couldNotRenameFileLocally'] = "Could not rename file locally (offline saved file)"
translations['en']['fabTakeImage'] = "Take photo and upload"
translations['en']['itemPublicLink'] = "Public link"
translations['en']['couldNotTrashItem'] = "Could not move __NAME__ to trash, please try again or contact support"
translations['en']['itemTrashed'] = "__NAME__ moved to trash"
translations['en']['trashItemHeader'] = "Move to trash"
translations['en']['trashItemsConfirmMessage'] = "Are you sure you want to move __COUNT__ items to the trash folder?"
translations['en']['cannotTrashItem'] = "Cannot move __NAME__ to trash"
translations['en']['cannotRenameItem'] = "Cannot rename __NAME__"
translations['en']['publicLinkHeader'] = "Public link __NAME__"
translations['en']['couldNotRestoreItem'] = "Could not restore __NAME__"
translations['en']['itemRestored'] = "__NAME__ restored"
translations['en']['restoreItem'] = "Restore"
translations['en']['removeFromShared'] = "Remove from shared"
translations['en']['stopSharing'] = "Stop sharing"
translations['en']['trashTitle'] = "Trash"
translations['en']['sharedInTitle'] = "Shared with me"
translations['en']['sharedOutTitle'] = "Currently sharing"
translations['en']['transfersMenuNoTransfers'] = "Uploads and downloads will show up here"
translations['en']['transfersMenuTitle'] = "Transfers"
translations['en']['trashEmptyPlaceholder'] = "Trash empty"
translations['en']['nothingInThisFolderYetPlaceholder'] = "There is nothing in this folder yet. Press the button at the bottom right to upload files or create a folder!"
translations['en']['folderHasNoContentsPlaceholder'] = "This folder has no content"
translations['en']['restoreItemsHeader'] = "Restore items"
translations['en']['restoreItemsConfirmMessage'] = "Are you sure you want to restore __COUNT__ items?"
translations['en']['fileExistsAtRestoreDestination'] = "__NAME__ exists at restore destination"
translations['en']['folderExistsAtRestoreDestination'] = "__NAME__ exists at restore destination"
translations['en']['newFolderName'] = "New folder name"
translations['en']['newFolderNamePlaceholder'] = "Folder name"
translations['en']['folderNameAlreadyExistsCreate'] = "__NAME__ already exists here"
translations['en']['folderCreated'] = "__NAME__ created"
translations['en']['shareItemUserNotFound'] = "__EMAIL__ not found"
translations['en']['shareItemFileNotFound'] = "__NAME__ not found"
translations['en']['shareFile'] = "Share file"
translations['en']['shareFolder'] = "Share folder"
translations['en']['couldNotShareItem'] = "Could not share __NAME__"
translations['en']['itemShared'] = "__NAME__ shared with __WITH__"
translations['en']['receiverEmail'] = "Receiver email"
translations['en']['cannotShareDefaultFolder'] = "You cannot share the default folder"
translations['en']['cannotShareWithSelf'] = "You cannot share an item with yourself"
translations['en']['shareTooBigForApp'] = "This folder is too big to be shared through the App. Please use the Browser File Manager."
translations['en']['transfersFinishing'] = "Finishing"
translations['en']['itemRemovedFromSharedIn'] = "__NAME__ removed"
translations['en']['itemStoppedSharing'] = "Stopped sharing __NAME__"
translations['en']['settingsHeader'] = "Settings"
translations['en']['darkMode'] = "Dark mode"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"
translations['en']['alertOkButton'] = "OK"

translations['nl']['close'] = "Sluit"
translations['nl']['cancel'] = "Annuleer"
translations['nl']['refresh'] = "Ververs"
translations['nl']['trashItem'] = "Prullenbak"
translations['nl']['moveItem'] = "Verplaats"
translations['nl']['myCloud'] = "Mijn Cloud"
translations['nl']['loginTitle'] = "Log in"
translations['nl']['registerTitle'] = "Maak een account"
translations['nl']['or'] = "of"
translations['nl']['loginButton'] = "Log in"
translations['nl']['registerButton'] = "Maak account"
translations['nl']['registerLink'] = "Maak een account (Eerste 10 GB gratis)"
translations['nl']['loginLink'] = "Log in"
translations['nl']['passwordRepeatPlaceholder'] = "Herhaal wachtwoord"
translations['nl']['emailPlaceholder'] = "E-mailadres"
translations['nl']['passwordPlaceholder'] = "Wachtwoord"
translations['nl']['2faPlaceholder'] = "2FA code (Laat veld leeg indien uitgeschakeld)"
translations['nl']['loginInvalidInputs'] = "Onjuist e-mailadres en wachtwoord"
translations['nl']['alertOkButton'] = "Ok"
translations['nl']['loginWrongCrednltials'] = "Onjuist e-mailadres, wachtwoord of 2FA code"
translations['nl']['apiRequestError'] = "Er is een fout opgetreden met uw verzoek, probeer het later opnieuw"
translations['nl']['registerInvalidFields'] = "Ongeldige formuliervelden"
translations['nl']['registerPasswordAtLeast10Chars'] = "Uw wachtwoord moet minimaal 10 tekens lang zijn"
translations['nl']['registerPasswordsDoNotMatch'] = "Wachtwoorden komen niet overeen"
translations['nl']['registerInvalidEmail'] = "Ongeldig e-mailadres"
translations['nl']['registerEmailAlreadyRegistered'] = "Het opgegeven e-mailadres is al geregistreerd"
translations['nl']['registerCouldNotSnldEmail'] = "Ok"
translations['nl']['alertOkButton'] = "We konden op dit moment geen e-mail verzenden, probeer het later opnieuw"
translations['nl']['registerSuccess'] = "Uw account is aangemaakt, bevestig uw e-mailadres door op de link te klikken die we naar u hebben toegestuurd"
translations['nl']['registerInvalidInputs'] = "Ongeldig e-mailadres, wachtwoord en bevestig wachtwoord"

translations['sv']['close'] = "Stäng"
translations['sv']['cancel'] = "Avbryt"
translations['sv']['refresh'] = "Uppdatera"
translations['sv']['trashItem'] = "Papperskorg"
translations['sv']['moveItem'] = "Flytta"
translations['sv']['myCloud'] = "Mitt Cloud"
translations['sv']['loginTitle'] = "Logga in"
translations['sv']['registerTitle'] = "Skapa Konto"
translations['sv']['or'] = "eller"
translations['sv']['loginButton'] = "Logga in"
translations['sv']['registerButton'] = "Skapa Konto"
translations['sv']['registerLink'] = "Skapa Konto (Första 10 GB gratis)"
translations['sv']['loginLink'] = "Logga in"
translations['sv']['passwordRepeatPlaceholder'] = "Upprepa lösenord"
translations['sv']['emailPlaceholder'] = "E-postadress"
translations['sv']['passwordPlaceholder'] = "Lösenord"
translations['sv']['2faPlaceholder'] = "2FA kod (Fyll endast i om 2FA är aktiverat)"
translations['sv']['loginInvalidInputs'] = "Fel E-postadress eller lösenord"
translations['sv']['alertOkButton'] = "OK"
translations['sv']['loginWrongCredentials'] = "Fel E-postadress, lösenord eller 2FA kod"
translations['sv']['apiRequestError'] = "Request error, försök igen"
translations['sv']['registerInvalidFields'] = "Ogiltliga formulärfält"
translations['sv']['registerPasswordAtLeast10Chars'] = "Ditt lösenord måste vara längre än 10"
translations['sv']['registerPasswordsDoNotMatch'] = "Lösenorden matchar inte"
translations['sv']['registerInvalidEmail'] = "Ogiltlig E-postadress"
translations['sv']['registerEmailAlreadyRegistered'] = "Denna E-postadress används redan"
translations['sv']['registerCouldNotSendEmail'] = "OK"
translations['sv']['alertOkButton'] = "Kunde ej skicka verifieringsmail, försök igen senare"
translations['sv']['registerSuccess'] = "Kontot skapades, vänligen verifiera ditt konto genom att klicka på länken som du fick via epost"
translations['sv']['registerInvalidInputs'] = "Fel E-postadress, lösenord och upprepa lösenord"
translations['sv']['sharedWithMe'] = "Delat med mig"
translations['sv']['currentlySharing'] = "Delas av mig"
translations['sv']['settings'] = "Inställningar"
translations['sv']['encryption'] = "Kryptering"
translations['sv']['help'] = "Hjälp"
translations['sv']['trash'] = "Papperskorg"
translations['sv']['userStorageUsageMenuText'] = "__PERCENTAGE__% av __MAX__ använt"
translations['sv']['goProBadge'] = "Gå Pro"
translations['sv']['unknownDeviceError'] = "Ett okänt fel inträffade, starta om applikationen eller kontakta support"

module.exports = {
    get: (lang = "en", text, firstUpperCase = true, replaceFrom = [], replaceTo = []) => {
        let gotText = translations[lang][text]

        if(!gotText){
            if(translations['en'][text]){
                return translations['en'][text]
            }

            return "NO_TRANSLATION_FOUND"
        }

        if(firstUpperCase){
            gotText = gotText.charAt(0).toUpperCase() + gotText.slice(1)
        }

        if(replaceFrom.length > 0 && replaceTo.length > 0){
            for(let i = 0; i < replaceFrom.length; i++){
                gotText = gotText.split(replaceFrom[i]).join(replaceTo[i])
            }
        }

        return gotText
    },
    isAvailable: (lang) => {
        if(typeof translations[lang] !== "undefined"){
            return true
        }

        return false
    }
}
